firstnum = int(input("Give me the first number: "))
secondnum = int(input("Give me the second number: "))
print("Thank you!")
print(f"{firstnum} + {secondnum} = {firstnum + secondnum}")
print(f"{firstnum} - {secondnum} = {firstnum - secondnum}")
print(f"{firstnum} / {secondnum} = {firstnum / secondnum}")
print(f"{firstnum} * {secondnum} = {firstnum * secondnum}")